version: 2.1

orbs:
  gh: circleci/github-cli@2.1.0

references:
  production_context: &production_context
    - npm
    - github

executors:
  publish-npm:
    docker:
      - image: oven/bun:1

jobs:
  publish-npm:
    executor: publish-npm
    steps:
      - gh/setup
      - checkout
      - run:
          name: Bun install
          command: bun install
      - run:
          name: Configure npm auth
          command: echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
      - run:
          name: Create Github release
          command: |
            export TAG=$(grep '"version":' ./package.json | cut -d\" -f4)
            gh release create -F CHANGELOG.md $TAG
      - run:
          name: Publish on npm
          command: bunx npm publish

workflows:
  release:
    when:
      matches:
        pattern: "^master$"
        value: << pipeline.git.branch >>
    jobs:
      - publish-npm:
          name: Publish on NPM
          context: *production_context
