version: 2.1

orbs:
  gh: circleci/github-cli@2.1.0

references:
  production_context: &production_context
    - npm
    - github

executors:
  publish-npm:
    docker:
      - image: cimg/node:22.15.1

jobs:
  publish-npm:
    executor: publish-npm
    steps:
      - gh/setup
      - checkout
      - run:
          name: Yarn install
          command: yarn
      - run:
          name: Create Github release
          command: |
            export TAG=$(grep '"version":' ./package.json | cut -d\" -f4)
            gh release create -F CHANGELOG.md $TAG
      - run:
          name: publish on npm
          command: yarn publish

workflows:
  release:
    when:
      matches:
        pattern: "^master$"
        value: << pipeline.git.branch >>
    jobs:
      - publish-npm:
          name: Publish on NPM
          context: *production_context
