const fields = [
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "text",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "number",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "email",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isMultiple: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "file",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "password",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "tel",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "address",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "url",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "date",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "dateRange",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "time",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "timeRange",
  },
  {
    isBooleanField: true,
    isDecisionField: false,
    isRepeatableDisabled: true,
    isRequiredDisabled: true,
    type: "switch",
  },
  {
    isBooleanField: true,
    isDecisionField: false,
    isRepeatableDisabled: true,
    isRequiredDisabled: true,
    type: "checkbox",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: true,
    isRequiredDisabled: true,
    type: "hidden",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: true,
    isRequiredDisabled: true,
    type: "tree",
  },
  {
    isBooleanField: false,
    isDecisionField: true,
    isRepeatableDisabled: true,
    isRequiredDisabled: false,
    type: "radio",
  },
  {
    isBooleanField: false,
    isDecisionField: true,
    isRepeatableDisabled: true,
    isRequiredDisabled: false,
    type: "select",
  },
  {
    initialQueryEnable: true,
    isBooleanField: false,
    isDecisionField: false,
    isRepeatableDisabled: true,
    isRequiredDisabled: false,
    type: "autocomplete",
  },
  {
    isBooleanField: false,
    isDecisionField: false,
    isMultiple: false,
    isRepeatableDisabled: false,
    isRequiredDisabled: false,
    type: "dynamicSelect",
  },
] as const;

export default fields;
