export const INPUT_TYPE = {
  address: "address",
  autocomplete: "autocomplete",
  checkbox: "checkbox",
  date: "date",
  daterange: "daterange",
  file: "file",
  hidden: "hidden",
  http: "http",
  number: "number",
  password: "password",
  radio: "radio",
  select: "select",
  switch: "switch",
  text: "text",
  time: "time",
  timerange: "timerange",
} as const;
